### ISSUE TITLE
have you reproduced the results in DORN paper

### ISSUE THREAD

**Issue by Liuyixuan95** [dontLoveBugs/DORN_pytorch#1]
hi,  have you reproduced the results in DORN paper?

**Comment by dontLoveBugs** [comment]
Not yet, I find it need much GPU memory and is time-consuming to train the network, but I have other more important  experiments to do.
I think the pytorch code need to be optimized. If you need to reproduce the results, you can try the official version in Caffe.

**Comment by Liuyixuan95** [comment]
@dontLoveBugs  
 I try your code , the result on validation is around 0.55(delta1). And on my own experiments, the result is around 0.76 , much lower  than the results mentioned on paper.

**Comment by suljaxm** [comment]
how to use the NYU Depth V2 dataset？ I have downloaded the file of nyu_depth_v2_labeled.mat, but I don't know how to work with them in the next.  
Could you please help me?

**Comment by jiaxinxie97** [comment]
@Liuyixuan95 
Did you try DORN on KITTI dataset? I also get results much lower than reported on KITTI dataset by using the model they provide .

**Comment by Liuyixuan95** [comment]
@jiaxinxie97  I tried DORN only on NYUv2, now the results are normal. By using the model they provide I can get high results.

**Comment by Liuyixuan95** [comment]
The training images are converted in NYU_depth_v2_raw. You can use the matlab code the official website offers.(there are demos you can refer to)

**Comment by jiaxinxie97** [comment]
@dontLoveBugs I used different groundtruth depthmap , so I get bad results. DORN interpolates spare depthmap into dense depthmap as groundtruth to train and evaluate, but I use spare depthmap to evaluate.

**Comment by suljaxm** [comment]
> @Liuyixuan95
> Did you try DORN on KITTI dataset? I also get results much lower than reported on KITTI dataset by using the model they provide .

Thanks,  Because v2 is too large, I first used the data of v1. However, when I registered the depth map and RGB map, I found that there would be some problems with the official tools. 
Matlab version is 2017a，and  I used matlab’s xunit4 on my path.  The error is as follows,
![0 1k rqcyc o qf pk tw](https://user-images.githubusercontent.com/32708865/50849245-623fd380-13b1-11e9-94c5-862f2523779e.png)

Is it my matlab version or plug-in?

**Comment by jiaxinxie97** [comment]
@Liuyixuan95 How do you evaluate DORN's results in NYUv2 dataset? I only find 654 test images in eigen split, but DORN said they used 694 images to test.

**Comment by suljaxm** [comment]
@jiaxinxie97 Friends, could you help me how to deal with the raw data on nyu_v2? I just do “nyu_depth_v2_labeled.mat“ now, but I dont know how to use all the Images (about 120k) in the dataset.

**Comment by Excelsiorwu** [comment]
> > @Liuyixuan95
> > Did you try DORN on KITTI dataset? I also get results much lower than reported on KITTI dataset by using the model they provide .
> 
> Thanks, Because v2 is too large, I first used the data of v1. However, when I registered the depth map and RGB map, I found that there would be some problems with the official tools.
> Matlab version is 2017a，and I used matlab’s xunit4 on my path. The error is as follows,
> ![0 1k rqcyc o qf pk tw](https://user-images.githubusercontent.com/32708865/50849245-623fd380-13b1-11e9-94c5-862f2523779e.png)
> 
> Is it my matlab version or plug-in?
I get the same problem as you. I think it is the difference between Windows and Linux .when run the code on ubuntu .The code works .It spend almost one week to process the datasets

**Comment by Liuyixuan95** [comment]
> @Liuyixuan95 How do you evaluate DORN's results in NYUv2 dataset? I only find 654 test images in eigen split, but DORN said they used 694 images to test.
@jiaxinxie97 
 I used 654 test images

**Comment by tjqansthd** [comment]
@Excelsiorwu  
Hi, In get_synched_frames function, modify
files = regexp(ls(sceneDir), '(\s+|\n)', 'split');
=> files = regexp(string(ls(sceneDir)), '(\n)', 'split');
It will work. I think it is a problem of different version.

**Comment by Excelsiorwu** [comment]
@tjqansthd  Hi,I  also think it is a problem of ''ls'' command return different things when you run Windows Matlab and Linux Matlab.   Thank you for your sharing

**Comment by stalin18** [comment]
@jiaxinxie97  "I tried DORN only on NYUv2, now the results are normal. By using the model they provide I can get high results."

Hey, can you clarify what do you mean? Do you mean to say that using the CAFFE models provided by authors gives you expected results? So the model implemented in this repository is slightly different ?
