### ISSUE TITLE
modification in OrdinalRegressionLayer?

### ISSUE THREAD

**Issue by jiaxinxie97** [dontLoveBugs/DORN_pytorch#11]
https://github.com/dontLoveBugs/DORN_pytorch/blob/0e982db5ffca4c0c947f3c40baed5a065276e19b/network/DORN_kitti.py#L217
  In line271 DORN_kitti.py, I find you output decode_c by summing all the probability. But in paper it counts channel with probability>0.5, your comments show similar operation in the paper. Can you tell me why?

**Comment by dontLoveBugs** [comment]
It seems a mistake. Thanks, I correct it.

**Comment by jiaxinxie97** [comment]
@dontLoveBugs 
https://github.com/dontLoveBugs/DORN_pytorch/blob/1836f824bea6866e05147e6715024559f25607b4/dataloaders/kitti_dataloader.py#L111
Another likely bug, you change ground truth depth by multiplying s? I think it only need divide 100.

**Comment by dontLoveBugs** [comment]
s is scale factor, which is to zoom in the  image and its groundtruth.

**Comment by jiaxinxie97** [comment]
Oh,thank you. But I am still confused about why change groundtruth with a random number. If you do that,  how to guarantee your output in a right scale? Or you mean because you zoom in the image so the groundtruth depth changes, you need to zoom it?

**Comment by swethavsd** [comment]
What is the size of the predicted ord labels from the Ordinal regression Layer? is it 1x71xHxW?
