### ISSUE TITLE
How to deal with the change of first layer of pretained model?

### ISSUE THREAD

**Issue by junweifu** [dontLoveBugs/DORN_pytorch#12]
In code,  the resnet-101 model is considered as pretained model in training.  When I load parameters from the official pretrained model, I find there is a error occurring because of a 3x3 kernal in the first conv layer insteading of 7x7. Can you tell me how to deal with this problem, thank you.

**Comment by XGuider** [comment]
yes,i meet  this problem too

**Comment by junweifu** [comment]
Thanks for the email from  @dontLoveBugs . I modify the loading pretrained model code from _backbone.py_ in the folder _network_. The parameters from conv1,bn1,conv2,bn2,conv3,bn3,layer1.0 should not be loaded. @XGuider

**Comment by XGuider** [comment]
@junweifu okay，i shall try.thnx!

**Comment by yearning-zenith** [comment]
Where do you guys got the pretrained weight for this backbone resnet since its architecuture is different from the original one

**Comment by dontLoveBugs** [comment]
Hi, I guess the backbone resnet is different from the pretrained model in PyTorch. Maybe, you should pretrain a ResNet whose first layer has three convolution.

**Comment by dontLoveBugs** [comment]
I think the pretrained model in pytorch also work. And you need replace  the three convs with the 7X7 conv in PyTorch.

**Comment by dontLoveBugs** [comment]
Whether a little difference in backbone has a great effect requires experimentation, but I have not verified it yet.

**Comment by yearning-zenith** [comment]
Since currently I only have limited computational resources and the result with 7X7 is not that good, could you share or tell me where I can get that pretrained weight for this special resnet?  I would appreciate your help.

**Comment by LCJHust** [comment]
> Thanks for the email from @dontLoveBugs . I modify the loading pretrained model code from _backbone.py_ in the folder _network_. The parameters from conv1,bn1,conv2,bn2,conv3,bn3,layer1.0 should not be loaded. @XGuider

Hi， I meet the same problems with you. Can you share the code block to show how to fix it? Thank you very much!

**Comment by LCJHust** [comment]
> Thanks for the email from @dontLoveBugs . I modify the loading pretrained model code from _backbone.py_ in the folder _network_. The parameters from conv1,bn1,conv2,bn2,conv3,bn3,layer1.0 should not be loaded. @XGuider

Thank you! I have fix the bugs!

**Comment by 111772** [comment]
> > Thanks for the email from @dontLoveBugs . I modify the loading pretrained model code from _backbone.py_ in the folder _network_. The parameters from conv1,bn1,conv2,bn2,conv3,bn3,layer1.0 should not be loaded. @XGuider
> 
> Hi， I meet the same problems with you. Can you share the code block to show how to fix it? Thank you very much!
Can everyone show me how to fix it ? i meet the same problem and i have no idea . Thanks!

**Comment by 111772** [comment]
> > Thanks for the email from @dontLoveBugs . I modify the loading pretrained model code from _backbone.py_ in the folder _network_. The parameters from conv1,bn1,conv2,bn2,conv3,bn3,layer1.0 should not be loaded. @XGuider
> 
> Thank you! I have fix the bugs!
>
Can everyone show me how to fix it ? i meet the same problem and i have no idea . Thanks!
