### ISSUE TITLE
Question about equation

### ISSUE THREAD

**Issue by abeyang00** [dontLoveBugs/DORN_pytorch#18]
In equation 4,

![Screenshot from 2019-05-15 11-07-02](https://user-images.githubusercontent.com/36392866/57743845-b95c0900-7701-11e9-9bda-bdcc96223d00.png)

what is the meaning of P(w,h)-1 part? do you know why  author is subtracting 1?

Thank you in advance

**Comment by dontLoveBugs** [comment]
It is the sum of cross-entropy loss of K binary classfication task.
