### ISSUE TITLE
What is the python version?

### ISSUE THREAD

**Issue by Fangyh09** [dontLoveBugs/DORN_pytorch#21]
Hello, what is the python version?

**Comment by dontLoveBugs** [comment]
Python version is 3.7 and Pytorch version 1.0 (>=1.2 is best).

**Comment by kk6398** [comment]
> Hello, what is the python version?

Hey,guys, I meet a difficult problem: I set the '-- c' parameter to the path of 'resnet101_v1c. pth' and attempt to run train.py, but encounter the following error: ruamel. yaml. reader. ReaderError: unacceptable character # x0080: invalid start byte. Could you help me deal this question? Is this step correct?   Thanks a lot.
