### ISSUE TITLE
Where to get splits.mat

### ISSUE THREAD

**Issue by icyhearts** [dontLoveBugs/DORN_pytorch#24]
Thanks for make the code open-sourced.
in tool/create_nyu_h5.py, this line
```
splilts = sio.loadmat(data_path + '/splits.mat')
```
where can we download splits.mat?

**Comment by shell769324** [comment]
https://cs.nyu.edu/~silberman/projects/indoor_scene_seg_sup.html

**Comment by dontLoveBugs** [comment]
Hi, this split data is not enough to reproduce the results of dorn. If you are interested in nyu dataset, I suggest you should download the whole dataset and you can refer to [this](https://github.com/janivanecky/Depth-Estimation/blob/master/dataset/README.txt)
