### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by brooda** [dontLoveBugs/DORN_pytorch#26]
Hi, 

I have a custom dataset, pairs of:
1. 400x400 RGB png image
2. 400x400 grayscale png image for depth - 1 is 1cm, so max depth is 2.55m.

Can you provide some information how can I use the solution on my dataset?

**Comment by dontLoveBugs** [comment]
If you want to finetune DORN to your custom dataset, you should resize your image size to 513x513, and maybe you need to decide how many depth subintervals you should discretize depth values, for example, if you hope accuracy is around 10cm, you should discretize depth values to 25 intervals (255cm / 10). Finally, you should finetune dorn in your dataset or train your from the scratch if you have enough data.
