### ISSUE TITLE
how to use the NYU Depth V2 dataset？

### ISSUE THREAD

**Issue by suljaxm** [dontLoveBugs/DORN_pytorch#3]
I have downloaded the file of nyu_depth_v2_labeled.mat, and turn it to a h5 file. but the running is error,
I don't know how to work with it in the next. 

![h5_error](https://user-images.githubusercontent.com/32708865/50519195-bff03800-0af4-11e9-8e65-0be0e066f108.png)

Could you please help me?

**Comment by dontLoveBugs** [comment]
Hi，it seems your convert code is different from ours. The '.h5' is a image, and yours looks like all of the images for training or testing.

**Comment by suljaxm** [comment]
Yes,  I don't know how to get these '.h5' images, and I directly converted from 'nyu_depth_v2_labeled.mat' in my way.  emmm, how to get your training data?  maybe, I just convert  'nyu_depth_v2_labeled.mat'  to a single '.h5' image, each data is a '.h5' image?

**Comment by dontLoveBugs** [comment]
I will provide our convert script.

**Comment by suljaxm** [comment]
Thanks~
