### ISSUE TITLE
Load model error

### ISSUE THREAD

**Issue by suljaxm** [dontLoveBugs/DORN_pytorch#4]
When I loaded the model, I found that the imported "state_dict" had a problem. I find that these keywords add an unexpected key(s) "module.XXX". the error as follows,
![fullsizerender 1](https://user-images.githubusercontent.com/32708865/51018878-18730b00-15b4-11e9-8db6-073ea47da47f.jpg)
I feel that all the parameters are one-to-one, but the loaded model just one more a prefixed with "module"

**Comment by suljaxm** [comment]
Ok, the problem was solved.

**Comment by suljaxm** [comment]
Because the number of my cuda devices is 1, I modified this condition.
![fullsizerender 2](https://user-images.githubusercontent.com/32708865/51082468-674eab00-1742-11e9-8608-8f9a39ab18d8.jpg)

**Comment by suljaxm** [comment]
Maybe this is a bug, because the code defaults to multi-card training as long as there is a cuda device.

**Comment by dontLoveBugs** [comment]
Hi, you can use the nn.DataParallel() whether you use multi-GPUs or not. If you use the nn.DataParallel(), you must use it  when you load the trained model. In order to avoid the bug, you can use the   nn.DataParallel() whether you use multi-GPUs or not.

**Comment by suljaxm** [comment]
Thank you, I will try next time. Now I am changed that condition ( if torch.cuda.device_count()>0) , and also can import model.

**Comment by dontLoveBugs** [comment]
You can refer to [this](https://github.com/janivanecky/Depth-Estimation/blob/master/dataset/README.txt)
