### ISSUE TITLE
train with nyu_depth_v2_labeled.mat is bad

### ISSUE THREAD

**Issue by SunskyF** [dontLoveBugs/DORN_pytorch#5]
no modify to origin code
use create_nyu_h5.py to convert nyu_depth_v2_labeled.mat
and use this small dataset to train
after 80 epoch, I get
![image](https://user-images.githubusercontent.com/10847418/51403186-a3429f80-1b8a-11e9-96be-72dc6ff18224.png)
seems strange

**Comment by dontLoveBugs** [comment]
Yes, if for training, you need much more pictures.

**Comment by SunskyF** [comment]
ok, thx
