### ISSUE TITLE
i want to ask you a question about alpha and beta

### ISSUE THREAD

**Issue by czy341181** [dontLoveBugs/DORN_pytorch#6]
in you code,your alpha and beta is 0.02 and 10 , do you calculate all the images in NYU?  I only download the 1449 NYU image and make use of your code cal_alpha_beta.py,and I got the alpha and beta,18 and 254. I want to know why, Is there a problem with my unit? Or my dataset? I would appreciate it if you could answer me.

**Comment by dontLoveBugs** [comment]
The alpha and beta is min and max depth value of the pictures which you use for training. 18 and 254 is too big and obviously is wrong, because NYU Depth is indoor dataset.  Maybe your depth data is wrong.

**Comment by czy341181** [comment]
Which dataset do you use? Is it downloaded from NYU official website? How many training datasets ?

**Comment by dontLoveBugs** [comment]
The raw dataset has almost 500G data and this paper(DORN) use 120k pictures. You can download 500G raw data and use  the matlab toolbox provided in official site to get much more pictures for training.
