### ISSUE TITLE
results on Kitti dataset

### ISSUE THREAD

**Issue by jiaxinxie97** [dontLoveBugs/DORN_pytorch#9]
Hi,
   Thank you for your sharing. I find you test kitti dataset in eigen spilt, can you tell me your results on this spilt?  
   Also, I want to ask which kind of groundtruth you use? For another word, is depthmap in train_gt16bit from kitti depth benchmark which is just released in these two years or projected from point clouds which are provided by raw data and much sparser.
   Last, if you use groundtruth provided in kitti depth benchmark, how do you get test_gt16bit? because only 652 images' groundtruth depth can be find in the benckmark.
   Thank you for you time!!

**Comment by jiaxinxie97** [comment]
From a closed issue I know you use depth groundtruth projected from point clouds. I still want to know your results, I trained it but didn't converge.

**Comment by dontLoveBugs** [comment]
I update the code and you can try it again.
